# RENAME THIS FILE TO config.py AND ADD YOUR KEYS

API_KEY = "YOUR_BYBIT_API_KEY"
API_SECRET = "YOUR_BYBIT_SECRET_KEY"
CRYPTOPANIC_TOKEN = "YOUR_CRYPTOPANIC_TOKEN"

# Settings
RISK_PER_TRADE = 5.0
MAX_POSITION_SIZE = 50.0
ATR_MULTIPLIER_SL = 2.0
ATR_MULTIPLIER_TP = 4.0
